### ISSUE TITLE
 process_action_link_action don't update row

### ISSUE THREAD

**Issue by markmcdonald51** [activescaffold/active_scaffold#469]
Hi All,

Something must have changed in the last few months since I checked  and it appears that ' process_action_link_action ' isn't sending out the right header.  It looks to be sending out the correct update on_action_update.js.erb but it just hangs. 

Does anyone know what this is not longer updating and refreshing the row via js?

Thanks in advance,
Mark

```erb
  <%
  events = @record.aasm.events.map(&:name)
  links = events.map do |event|
    link_to(event .to_s.titleize, state_change_google_search_result_path(@record, 
      { event: event}), method: :put, remote: true) 
  end
 
    %>  

    <%= display_dynamic_action_group active_scaffold_config.action_links[:get_states],
   links, @record, :class => 'report_submenu' %>
```

   (0.0ms)  begin transaction
  SQL (0.1ms)  UPDATE "google_search_results" SET "aasm_state" = ?, "updated_at" = ? WHERE "google_search_results"."id" = ?  [["aasm_state", "rejected"], ["updated_at", "2016-01-14 22:54:07.924898"], ["id", 2996]]
   (8.6ms)  commit transaction
  Rendered /home/hounddog/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/active_scaffold-3.4.18.1/app/views/active_scaffold_overrides/_messages.html.erb (0.9ms)
  Rendered /home/hounddog/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/active_scaffold-3.4.18.1/app/views/active_scaffold_overrides/_update_messages.js.erb (6.0ms)
  Rendered /home/hounddog/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/active_scaffold-3.4.18.1/app/views/active_scaffold_overrides/_list_record.html.erb (4.0ms)
  Rendered /home/hounddog/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/active_scaffold-3.4.18.1/app/views/active_scaffold_overrides/_update_calculations.js.erb (0.4ms)
  Rendered /home/hounddog/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/active_scaffold-3.4.18.1/app/views/active_scaffold_overrides/on_action_update.js.erb (19.5ms)
Completed 200 OK in 40ms (Views: 25.4ms | ActiveRecord: 9.1ms)

**Comment by scambra** [comment]
Can you check network tab on web inspector? Check response, if it has right JS, and response headers, content-type should have text/javascript

**Comment by markmcdonald51** [comment]
Hi Scambra,

It is returning js (I have attached the image). It is calling the method state_change and performing the correct actions bit it doesnt update/refresh the row. This used to work and I wrestled with this yesterday as I did something very similar before...so when I got home I looked at the program that worked before and it too wasn't working anymore. 

Thanks for your help. I really would love to get this working correctly --that is re-rendering the updated row!

Mark
![screenshot from 2016-01-14 15 27 54](https://cloud.githubusercontent.com/assets/39400/12355801/290ead38-bb6d-11e5-871d-fdbb2df00763.png)

**Comment by markmcdonald51** [comment]
Here is another shot of just the network inspector of that js action:

![screenshot from 2016-01-14 15 36 08](https://cloud.githubusercontent.com/assets/39400/12355858/7fb3e324-bb6d-11e5-950f-1be3fdfa97a5.png)

**Comment by scambra** [comment]
Ok, so headers are right.

Is JS response right? Is there any line like this?
```js
ActiveScaffold.find_action_link('...').close('row html code')
```

You can try copying every line from response and paste on console tab, to check if it works

**Comment by markmcdonald51** [comment]
Hi Sergio,
Not sure what to make of this... I open this app up in Chromium and turned on the web developer mode and got this when I clicked the action link:

Uncaught TypeError: Cannot read property 'loading_indicator' of undefined

Would that be enough to stop this for working correctly?
I have attached the error in the window.

Thanks for looking into this!

Mark
![screenshot from 2016-01-19 10 22 42](https://cloud.githubusercontent.com/assets/39400/12422861/eb81ada8-be96-11e5-8d41-db69b31b76d0.png)

**Comment by scambra** [comment]
Not sure, but probably
When you click activate, do you get a spinning icon?
Also, try adding as_action class to your links:

```ruby
link_to(event .to_s.titleize, state_change_google_search_result_path(@record, 
      { event: event}), method: :put, remote: true, class: 'as_action')

**Comment by scambra** [comment]
Probably JS is fixed on master, can you check?

**Comment by markmcdonald51** [comment]
Hi Sergio. 

I just did a gem update and reloaded the server to see that it is still hanging... I have not tried to do any of the javascript/jquery suggestions above  but I will try to get to this later and get back to this when I do.

Thanks Sergio!
Ciao for now.
